# -*- mode: python ; coding: utf-8 -*-
import os
import sys
from PyInstaller.utils.hooks import collect_data_files, collect_submodules

block_cipher = None
ROOT = r'D:\S.A.T.U.R.D.A.Y'
PYTHON = os.path.dirname(sys.executable) if sys.executable else r'D:\Python312'

a = Analysis(
    [os.path.join(ROOT, 'saturday_launcher_exe.py')],
    pathex=[ROOT, os.path.join(ROOT, 'core'), PYTHON],
    binaries=[],
    datas=[
        (os.path.join(ROOT, 'core', 'ui', 'templates'), 'core/ui/templates'),
        (os.path.join(ROOT, 'core', 'ui', 'static'), 'core/ui/static'),
        (os.path.join(ROOT, 'data'), 'data'),
        (os.path.join(ROOT, '.env'), '.'),
    ],
    hiddenimports=[
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'fastapi',
        'starlette',
        'structlog',
        'psutil',
        'numpy',
        'pydantic',
        'jinja2',
        'aiohttp',
        'requests',
        'paho.mqtt',
        'pystray',
        'PIL',
        'cv2',
        'mediapipe',
        'sounddevice',
        'speech_recognition',
        'pyttsx3',
        'edge_tts',
        'scipy',
        'sklearn',
        'onnxruntime',
        'selenium',
        'firebase_admin',
        'google.auth',
        'google.oauth2',
        'googleapiclient',
        'dotenv',
        'httpx',
        'huggingface_hub',
        'tokenizers',
        'transformers',
        'ctransformers',
        'typing_inspection',
        'pywin32',
        'win32gui',
        'win32con',
        'win32api',
        'win32ts',
        'webbrowser',
        'threading',
        'asyncio',
        'json',
        'logging',
        'hashlib',
        'math',
        'wave',
        'io',
        'base64',
        'importlib',
        'pathlib',
        'signal',
        'gc',
        'shutil',
        'platform',
        'uuid',
        'collections',
        'datetime',
        'time',
        're',
        'os',
        'sys',
        'random',
        'argparse',
        'subprocess',
        'csv',
        'ast',
        'inspect',
        'traceback',
        'textwrap',
        'functools',
        'operator',
        'itertools',
        'copy',
        'pprint',
        'warnings',
        'enum',
        'dataclasses',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'pytest',
        'unittest',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='SATURDAY',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='SATURDAY',
)
