# -*- mode: python ; coding: utf-8 -*-
import os
import sys
from PyInstaller.utils.hooks import collect_data_files, collect_submodules

block_cipher = None
ROOT = r'D:\S.A.T.U.R.D.A.Y'
PYTHON = os.path.dirname(sys.executable) if sys.executable else r'D:\Python312'

a = Analysis(
    [os.path.join(ROOT, 'saturday_launcher_exe.py')],
    pathex=[ROOT, os.path.join(ROOT, 'core'), PYTHON],
    binaries=[],
    datas=[
        (os.path.join(ROOT, 'core', 'ui', 'templates'), 'core/ui/templates'),
        (os.path.join(ROOT, 'core', 'ui', 'static'), 'core/ui/static'),
        (os.path.join(ROOT, 'data'), 'data'),
        (os.path.join(ROOT, '.env'), '.'),
        (os.path.join(ROOT, 'core', 'ui', 'templates'), 'core/ui/templates'),
        (os.path.join(ROOT, 'core', 'ui', 'static'), 'core/ui/static'),
    ],
    hiddenimports=[
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'fastapi',
        'starlette',
        'structlog',
        'psutil',
        'numpy',
        'pydantic',
        'jinja2',
        'aiohttp',
        'requests',
        'paho.mqtt',
        'pystray',
        'PIL',
        'cv2',
        'mediapipe',
        'sounddevice',
        'speech_recognition',
        'pyttsx3',
        'edge_tts',
        'scipy',
        'sklearn',
        'onnxruntime',
        'selenium',
        'firebase_admin',
        'google.auth',
        'google.oauth2',
        'googleapiclient',
        'dotenv',
        'httpx',
        'huggingface_hub',
        'tokenizers',
        'transformers',
        'ctransformers',
        'typing_inspection',
        'pywin32',
        'win32gui',
        'win32con',
        'win32api',
        'win32ts',
        'webbrowser',
        'threading',
        'asyncio',
        'json',
        'logging',
        'hashlib',
        'math',
        'wave',
        'io',
        'base64',
        'importlib',
        'pathlib',
        'signal',
        'gc',
        'shutil',
        'platform',
        'uuid',
        'collections',
        'datetime',
        'time',
        're',
        'os',
        'sys',
        'random',
        'argparse',
        'subprocess',
        'csv',
        'ast',
        'inspect',
        'traceback',
        'textwrap',
        'functools',
        'operator',
        'itertools',
        'copy',
        'pprint',
        'warnings',
        'enum',
        'dataclasses',
        # Core SATURDAY modules
        'core.runtime',
        'core.config',
        'core.state',
        'core.rbac',
        'core.event_bus',
        'core.human_interface',
        'core.cloud_bridge',
        'core.secure_gateway_mount',
        'core.system_tray',
        'core.sound_monitor',
        'core.alert_manager',
        'core.brain',
        'core.greeting',
        'core.spatial_audio',
        'core.window_manager',
        'core.self_heal',
        'core.self_healing',
        'core.admin_mood',
        'core.self_rewrite',
        'core.learning_manager',
        'core.usb_watchdog',
        'core.remote_desktop',
        'core.voice_dl',
        'core.persona',
        'core.task_manager',
        'core.agent_service',
        'core.logging_config',
        # AI modules
        'ai_modules.llm_engine',
        'ai_modules.code_writer',
        'ai_modules.security_assistant',
        'ml_integration.core',
        'ml_integration.predictor',
        'ml_integration.nlp',
        'conversational_dl.engine',
        'deep_learning.core',
        'deep_learning.policy',
        'deep_learning.adaptive',
        'deep_learning.patterns',
        'deep_learning.evolution',
        'deep_learning.backend',
        # Communication
        'communication.speech',
        'communication.call_agent',
        'communication.livekit_webhooks',
        'communication.livekit_bridge',
        'communication.screen_navigator',
        'communication.social_agent',
        'communication.voice_command_router',
        'communication.whatsapp_navigator',
        'communication.insta_navigator',
        # Services
        'services.web_search',
        'services.music_manager',
        'services.weather_service',
        'services.news_service',
        # Governance
        'governance.policy',
        'governance.consent_manager',
        'governance.privacy_mode',
        'governance.compliance_logger',
        'governance.biometric_policy',
        # Identity
        'identity.manager',
        'identity.face_id',
        'identity.voice_id',
        'identity.voice_biometric',
        # Health
        'health.monitor',
        'health.google_fit_integration',
        'health.sensor_hub',
        'health.fusion',
        'health.fall_prediction',
        'health.doctor_mode',
        'health.rppg_engine',
        # UI
        'ui.bridge',
        'ui.voice_interface',
        'ui.websocket_bridge',
        'ui.notification_handler',
        'ui.edith_voice',
        # Hybrid
        'hybrid.main',
        'hybrid.edith.main',
        'hybrid.edith.task_handler',
        # Distributed
        'distributed',
        'distributed.interdevice_sync',
        # Vision
        'embodied.vision',
        # Christianity
        'christianity_core.spirituality',
        # HomeBot
        'core.homebot_integration',
        # Orchestrator
        'orchestrator.showtime_manager',
        # Obsidian
        'obsidian_brain',
        # Integration
        'integration.ros2_bridge',
        'integration.sync_node',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'pytest',
        'unittest',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='SATURDAY',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='SATURDAY',
)
